apiVersion: v1
kind: Service
metadata:
  name: csc8567-service
spec:
  type: NodePort  # Le service sera exposé sur un port du nœud
  selector:
    app: csc8567  # Il doit correspondre aux labels définis dans le Deployment
  ports:
    - protocol: TCP
      port: 80  # Le port interne utilisé par le conteneur
      targetPort: 5000
      nodePort: 30008  # Un port dans la plage 30000-32767
