# Utilise l'image officielle de Python comme image de base
FROM python:3.10

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers de dépendances dans le conteneur
COPY requirements.txt ./

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Copier le code source dans le conteneur
COPY . .

# Exposer le port que l'application utilise
EXPOSE 8801

# Commande par défaut pour lancer le script de démarrage
CMD ["bash", "run_api.sh"]
