# Utiliser l'image Python comme base
FROM python:3.10

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers de dépendances
COPY requirements.txt .

# Installer les dépendances
RUN python3 -m venv /venv \
    && /venv/bin/pip install --upgrade pip \
    && /venv/bin/pip install -r requirements.txt

# Copier le reste du code du projet
COPY . .

# Définir la variable d'environnement pour utiliser l'environnement virtuel
ENV PATH="/venv/bin:$PATH"

# Exposer le port 8800
EXPOSE 8800

# Commande par défaut pour lancer le serveur
CMD ["bash", "run_web.sh"]
