FROM mariadb:latest

# Copier vos scripts d'initialisation, si nécessaire
COPY init.sql /docker-entrypoint-initdb.d/
COPY check_bd.sh /usr/local/bin/check_mysql.sh

# Donnez les bonnes permissions à votre script
RUN chmod +x /usr/local/bin/check_mysql.sh

# Installe mysql-client pour utiliser mysqladmin et mysql
RUN apt-get update && apt-get install -y mysql-client
